language: go
go:
  - 1.11

branches:
  only:
    - master

# this downloads and unpacks netlifyctl
before_install:
  - wget https://github.com/netlify/netlifyctl/releases/download/v0.3.2/netlifyctl-linux-amd64-0.3.2.tar.gz
  - tar -xvf netlifyctl-linux-amd64-0.3.2.tar.gz

script:
  - ./s/travis_build.sh

# Skip the install step (go get ./...) because we use modules and "go get" fails
install: true